//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_mercadopago
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LOLIMSASER", ConfigurationName="ws_mercadopago.ws_lolimsaservicesSoapPort")]
    public interface ws_lolimsaservicesSoapPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="LOLIMSASERaction/AWS_LOLIMSASERVICES.MERCADOPAGO", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_mercadopago.MERCADOPAGOResponse> MERCADOPAGOAsync(ws_mercadopago.MERCADOPAGORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LOLIMSASERaction/AWS_LOLIMSASERVICES.GETPAYMENTMP", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_mercadopago.GETPAYMENTMPResponse> GETPAYMENTMPAsync(ws_mercadopago.GETPAYMENTMPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LOLIMSASERaction/AWS_LOLIMSASERVICES.CREARSTORE", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_mercadopago.CREARSTOREResponse> CREARSTOREAsync(ws_mercadopago.CREARSTORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LOLIMSASERaction/AWS_LOLIMSASERVICES.CREARCAJA", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_mercadopago.CREARCAJAResponse> CREARCAJAAsync(ws_mercadopago.CREARCAJARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LOLIMSASERaction/AWS_LOLIMSASERVICES.CREARORDEN", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_mercadopago.CREARORDENResponse> CREARORDENAsync(ws_mercadopago.CREARORDENRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LOLIMSASERaction/AWS_LOLIMSASERVICES.CANCELARORDEN", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_mercadopago.CANCELARORDENResponse> CANCELARORDENAsync(ws_mercadopago.CANCELARORDENRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LOLIMSASERaction/AWS_LOLIMSASERVICES.SEARCHORDEN", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_mercadopago.SEARCHORDENResponse> SEARCHORDENAsync(ws_mercadopago.SEARCHORDENRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.MERCADOPAGO", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class MERCADOPAGORequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Request;
        
        public MERCADOPAGORequest()
        {
        }
        
        public MERCADOPAGORequest(string Request)
        {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.MERCADOPAGOResponse", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class MERCADOPAGOResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Result;
        
        public MERCADOPAGOResponse()
        {
        }
        
        public MERCADOPAGOResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.GETPAYMENTMP", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class GETPAYMENTMPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Request;
        
        public GETPAYMENTMPRequest()
        {
        }
        
        public GETPAYMENTMPRequest(string Request)
        {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.GETPAYMENTMPResponse", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class GETPAYMENTMPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Result;
        
        public GETPAYMENTMPResponse()
        {
        }
        
        public GETPAYMENTMPResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.CREARSTORE", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class CREARSTORERequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Request;
        
        public CREARSTORERequest()
        {
        }
        
        public CREARSTORERequest(string Request)
        {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.CREARSTOREResponse", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class CREARSTOREResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Result;
        
        public CREARSTOREResponse()
        {
        }
        
        public CREARSTOREResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.CREARCAJA", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class CREARCAJARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Request;
        
        public CREARCAJARequest()
        {
        }
        
        public CREARCAJARequest(string Request)
        {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.CREARCAJAResponse", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class CREARCAJAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Result;
        
        public CREARCAJAResponse()
        {
        }
        
        public CREARCAJAResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.CREARORDEN", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class CREARORDENRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Request;
        
        public CREARORDENRequest()
        {
        }
        
        public CREARORDENRequest(string Request)
        {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.CREARORDENResponse", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class CREARORDENResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Result;
        
        public CREARORDENResponse()
        {
        }
        
        public CREARORDENResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.CANCELARORDEN", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class CANCELARORDENRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Request;
        
        public CANCELARORDENRequest()
        {
        }
        
        public CANCELARORDENRequest(string Request)
        {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.CANCELARORDENResponse", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class CANCELARORDENResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Result;
        
        public CANCELARORDENResponse()
        {
        }
        
        public CANCELARORDENResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.SEARCHORDEN", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class SEARCHORDENRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Request;
        
        public SEARCHORDENRequest()
        {
        }
        
        public SEARCHORDENRequest(string Request)
        {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ws_lolimsaservices.SEARCHORDENResponse", WrapperNamespace="LOLIMSASER", IsWrapped=true)]
    public partial class SEARCHORDENResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="LOLIMSASER", Order=0)]
        public string Result;
        
        public SEARCHORDENResponse()
        {
        }
        
        public SEARCHORDENResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ws_lolimsaservicesSoapPortChannel : ws_mercadopago.ws_lolimsaservicesSoapPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ws_lolimsaservicesSoapPortClient : System.ServiceModel.ClientBase<ws_mercadopago.ws_lolimsaservicesSoapPort>, ws_mercadopago.ws_lolimsaservicesSoapPort
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ws_lolimsaservicesSoapPortClient() : 
                base(ws_lolimsaservicesSoapPortClient.GetDefaultBinding(), ws_lolimsaservicesSoapPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ws_lolimsaservicesSoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_lolimsaservicesSoapPortClient(EndpointConfiguration endpointConfiguration) : 
                base(ws_lolimsaservicesSoapPortClient.GetBindingForEndpoint(endpointConfiguration), ws_lolimsaservicesSoapPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_lolimsaservicesSoapPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ws_lolimsaservicesSoapPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_lolimsaservicesSoapPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ws_lolimsaservicesSoapPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_lolimsaservicesSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_mercadopago.MERCADOPAGOResponse> ws_mercadopago.ws_lolimsaservicesSoapPort.MERCADOPAGOAsync(ws_mercadopago.MERCADOPAGORequest request)
        {
            return base.Channel.MERCADOPAGOAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_mercadopago.MERCADOPAGOResponse> MERCADOPAGOAsync(string Request)
        {
            ws_mercadopago.MERCADOPAGORequest inValue = new ws_mercadopago.MERCADOPAGORequest();
            inValue.Request = Request;
            return ((ws_mercadopago.ws_lolimsaservicesSoapPort)(this)).MERCADOPAGOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_mercadopago.GETPAYMENTMPResponse> ws_mercadopago.ws_lolimsaservicesSoapPort.GETPAYMENTMPAsync(ws_mercadopago.GETPAYMENTMPRequest request)
        {
            return base.Channel.GETPAYMENTMPAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_mercadopago.GETPAYMENTMPResponse> GETPAYMENTMPAsync(string Request)
        {
            ws_mercadopago.GETPAYMENTMPRequest inValue = new ws_mercadopago.GETPAYMENTMPRequest();
            inValue.Request = Request;
            return ((ws_mercadopago.ws_lolimsaservicesSoapPort)(this)).GETPAYMENTMPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_mercadopago.CREARSTOREResponse> ws_mercadopago.ws_lolimsaservicesSoapPort.CREARSTOREAsync(ws_mercadopago.CREARSTORERequest request)
        {
            return base.Channel.CREARSTOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_mercadopago.CREARSTOREResponse> CREARSTOREAsync(string Request)
        {
            ws_mercadopago.CREARSTORERequest inValue = new ws_mercadopago.CREARSTORERequest();
            inValue.Request = Request;
            return ((ws_mercadopago.ws_lolimsaservicesSoapPort)(this)).CREARSTOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_mercadopago.CREARCAJAResponse> ws_mercadopago.ws_lolimsaservicesSoapPort.CREARCAJAAsync(ws_mercadopago.CREARCAJARequest request)
        {
            return base.Channel.CREARCAJAAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_mercadopago.CREARCAJAResponse> CREARCAJAAsync(string Request)
        {
            ws_mercadopago.CREARCAJARequest inValue = new ws_mercadopago.CREARCAJARequest();
            inValue.Request = Request;
            return ((ws_mercadopago.ws_lolimsaservicesSoapPort)(this)).CREARCAJAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_mercadopago.CREARORDENResponse> ws_mercadopago.ws_lolimsaservicesSoapPort.CREARORDENAsync(ws_mercadopago.CREARORDENRequest request)
        {
            return base.Channel.CREARORDENAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_mercadopago.CREARORDENResponse> CREARORDENAsync(string Request)
        {
            ws_mercadopago.CREARORDENRequest inValue = new ws_mercadopago.CREARORDENRequest();
            inValue.Request = Request;
            return ((ws_mercadopago.ws_lolimsaservicesSoapPort)(this)).CREARORDENAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_mercadopago.CANCELARORDENResponse> ws_mercadopago.ws_lolimsaservicesSoapPort.CANCELARORDENAsync(ws_mercadopago.CANCELARORDENRequest request)
        {
            return base.Channel.CANCELARORDENAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_mercadopago.CANCELARORDENResponse> CANCELARORDENAsync(string Request)
        {
            ws_mercadopago.CANCELARORDENRequest inValue = new ws_mercadopago.CANCELARORDENRequest();
            inValue.Request = Request;
            return ((ws_mercadopago.ws_lolimsaservicesSoapPort)(this)).CANCELARORDENAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_mercadopago.SEARCHORDENResponse> ws_mercadopago.ws_lolimsaservicesSoapPort.SEARCHORDENAsync(ws_mercadopago.SEARCHORDENRequest request)
        {
            return base.Channel.SEARCHORDENAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_mercadopago.SEARCHORDENResponse> SEARCHORDENAsync(string Request)
        {
            ws_mercadopago.SEARCHORDENRequest inValue = new ws_mercadopago.SEARCHORDENRequest();
            inValue.Request = Request;
            return ((ws_mercadopago.ws_lolimsaservicesSoapPort)(this)).SEARCHORDENAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_lolimsaservicesSoapPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_lolimsaservicesSoapPort))
            {
                return new System.ServiceModel.EndpointAddress("http://200.121.128.122:8010/LOLIMSASER/servlet/com.lolimsaser.aws_lolimsaservices" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ws_lolimsaservicesSoapPortClient.GetBindingForEndpoint(EndpointConfiguration.ws_lolimsaservicesSoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ws_lolimsaservicesSoapPortClient.GetEndpointAddress(EndpointConfiguration.ws_lolimsaservicesSoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ws_lolimsaservicesSoapPort,
        }
    }
}
